[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ExactDiagonalization = "52dcaa32-6da7-11e9-20ef-755843cf72eb"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
GRAPE = "6b52fcaf-80fe-489a-93e9-9f92080510be"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Lattices = "c21dee59-005f-55b6-acfd-94526b082a96"
NLSolvers = "337daf1e-9722-11e9-073e-8b9effe078ba"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumControl = "8a270532-f23f-47a8-83a9-b33d10cad486"
QuantumLattices = "78ae1a1f-1d5d-5174-b61c-66e31b2346dc"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
